services:
  data_provider:
    build: .
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs:/data_provider/logs
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_configs/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq_configs/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
    rabbitmq_data:
    logs_volume:

