services:
  data_provider:
    image: clar1ssesousa/data_provider:latest
    container_name: data-provider
    volumes:
      - ./logs:/data_provider/logs
      - ./configs:/data_provider/configs
      - ./house_files:/data_provider/house_files
    environment:
      - DOCKER_USERNAME=${USERNAME}
      - DOCKER_PASSWORD=${PASSWORD}
    restart: always
    networks:
      - opeva_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_data_provider
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_USERNAME=$[USERNAME}
      - WATCHTOWER_PASSWORD=${PASSWORD}
    restart: always
    networks:
      - opeva_network

volumes:
  logs_volume:
  configs:
  house_files:

networks:
  opeva_network:
    external: true







