@startuml LVL1
!define COLOR #5B9BD5

actor "Cleanwatts" as CWCliente COLOR
actor "i-charging" as ICCliente COLOR
participant "i-charging" as ICharging COLOR
participant "RabbitMQ" as Rabbit COLOR
participant "Runtime Decision System" as Sistema COLOR
participant "Cleanwatts" as Cleanwatts COLOR
participant "API Preço da Energia" as APIPreco COLOR

Sistema -> Cleanwatts : POST /sessions
activate Sistema
activate Cleanwatts
Cleanwatts --> Sistema : 201 Created
deactivate Cleanwatts
loop
    Sistema -> Cleanwatts : GET /data/lastvalue/Instant?tags=deviceID
    activate Cleanwatts
    Cleanwatts --> Sistema : 200 Ok
    deactivate Cleanwatts
    Sistema -> Sistema : translate(house_name, message)
end

ICharging -> Rabbit : Envia Dados
activate Rabbit
Rabbit -> Sistema : Consome Dados
deactivate Rabbit

Sistema -> Sistema : translate(house_name, devices, message)
Sistema -> Sistema : Processa e Agrupa Dados
Sistema -> APIPreco : GET /price
activate APIPreco
APIPreco --> Sistema : 200 Ok
deactivate APIPreco
Sistema -> Sistema : Gera Decisões
deactivate Sistema

ICCliente -> Sistema : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga

activate ICCliente
activate Sistema
Sistema -> ICCliente : Envia Decisões
deactivate Sistema
deactivate ICCliente

CWCliente -> Sistema : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
activate CWCliente
activate Sistema
Sistema -> CWCliente : Envia Decisões
deactivate Sistema
deactivate CWCliente

@enduml
