@startuml LVL1
!define COLOR #5B9BD5

actor "Cleanwatts" as CWCliente COLOR
actor "i-charging" as ICCliente COLOR
participant "i-charging" as ICharging COLOR
participant "RabbitMQ (i-charging)" as RabbitIC COLOR
participant "Translator System" as SistemaTRANS COLOR
participant "Cleanwatts" as Cleanwatts COLOR
participant "Residential Decision System" as SistemaRD COLOR
participant "Training System" as SistemaTRAIN COLOR
participant "RabbitMQ (System)" as RabbitSYS COLOR

SistemaTRANS -> Cleanwatts : POST /sessions
activate SistemaTRANS
activate Cleanwatts
Cleanwatts --> SistemaTRANS : 201 Created
Cleanwatts --> SistemaTRANS : Erro
deactivate Cleanwatts

loop
    SistemaTRANS -> Cleanwatts : GET /data/lastvalue/Instant?tags=deviceID
    activate Cleanwatts
    Cleanwatts --> SistemaTRANS : 200 Ok message
    deactivate Cleanwatts
    SistemaTRANS -> SistemaTRANS : translate(house_name, message)
end

ICharging -> RabbitIC : Envia Dados

activate RabbitIC
RabbitIC -> SistemaTRANS : Consome os Dados
deactivate RabbitIC

SistemaTRANS -> SistemaTRANS : translate(house_name, devices, message)
SistemaTRANS -> SistemaTRANS : Processa e Agrupa Dados de ambas as fontes

SistemaTRANS -> RabbitSYS : Envia Dados Processados para a queue da casa a que pertencem os dados
deactivate SistemaTRANS
activate RabbitSYS

RabbitSYS -> SistemaTRAIN : Consome os Dados
RabbitSYS -> SistemaRD : Consome os Dados
deactivate RabbitSYS

activate SistemaRD

SistemaRD -> SistemaRD : Processa Dados e Gera Decisões


ICCliente -> SistemaRD : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
activate ICCliente
SistemaRD -> ICCliente : Envia Decisões
deactivate ICCliente

CWCliente -> SistemaRD : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
activate CWCliente
SistemaRD -> CWCliente : Envia Decisões
deactivate CWCliente

deactivate SistemaRD

@enduml
