@startuml LVL1
!define COLOR #5B9BD5

actor "Cleanwatts" as CWCliente COLOR
actor "i-charging" as ICCliente COLOR
participant "CWReceiver" as CWReceiver COLOR
participant "Cleanwatts" as Cleanwatts COLOR
participant "i-charging" as ICharging COLOR
participant "RabbitMQ (i-charging)" as RabbitIC COLOR
participant "ICReceiver" as ICReceiver COLOR
participant "CWTranslator" as CWTranslator COLOR
participant "ICTranslator" as ICTranslator COLOR
participant "CWDecisionForwarder" as CWDecisionForwarder COLOR
participant "ICDecisionForwarder" as ICDecisionForwarder COLOR
participant "EnergyPrice" as EnergyPrice COLOR
participant "DataReceiver (MessageAggregator)" as DataReceiverMA COLOR
participant "MessageAggregator" as MessageAggregator COLOR
participant "DataReceiver (AlgorithmReceiver)" as DataReceiverAR COLOR
participant "AlgorithmReceiver" as AlgorithmReceiver COLOR
participant "Algorithm" as Algorithm COLOR
participant "RabbitMQ (System)" as RabbitSYS COLOR

CWReceiver -> Cleanwatts : POST /sessions
activate CWReceiver
activate Cleanwatts
Cleanwatts --> CWReceiver : 201 Created
deactivate Cleanwatts

loop
    CWReceiver -> Cleanwatts : GET /data/lastvalue/Instant?tags=deviceID
    activate Cleanwatts
    Cleanwatts --> CWReceiver : 200 Ok message
    deactivate Cleanwatts
    CWReceiver -> CWTranslator : translate(house_name, message)
    deactivate CWReceiver
    activate CWTranslator
    CWTranslator -> RabbitSYS : Envia os dados filtrados do Estado Energético da Instalaçã0
    deactivate CWTranslator
    activate RabbitSYS
end

ICharging -> RabbitIC : Envia Dados referentes ao Estado Energético da Instalação

activate RabbitIC
RabbitIC -> ICReceiver : Consome os Dados
deactivate RabbitIC

activate ICReceiver
ICReceiver -> ICTranslator : translate(house_name, devices, message
deactivate ICReceiver

activate ICTranslator
ICTranslator -> RabbitSYS : Envia os dados filtrados do Estado Energético da Instalação
deactivate ICTranslator

loop
RabbitSYS -> DataReceiverMA : Consome os Dados
deactivate RabbitSYS

activate DataReceiverMA
DataReceiverMA -> MessageAggregator: Encaminha dados
deactivate DataReceiverMA

activate MessageAggregator
MessageAggregator -> MessageAggregator : Processa e Agrupa Dados
end

MessageAggregator -> RabbitSYS : Envia Dados Processados para a queue da casa a que pertencem os dados
deactivate MessageAggregator


activate RabbitSYS
RabbitSYS -> DataReceiverAR : Consome os Dados
deactivate RabbitSYS

activate DataReceiverAR
DataReceiverAR -> AlgorithmReceiver : Encaminha dados
deactivate DataReceiverAR

activate AlgorithmReceiver
AlgorithmReceiver -> Algorithm : Envia Dados ao Algoritmo

deactivate AlgorithmReceiver
activate Algorithm
Algorithm -> Algorithm : Processa Dados e Gera Decisões
Algorithm --> AlgorithmReceiver : Envia Decisões
deactivate Algorithm

activate AlgorithmReceiver
AlgorithmReceiver -> ICDecisionForwarder : Envia Decisões de dispositivos da i-charging
AlgorithmReceiver -> CWDecisionForwarder : Envia Decisões de dispositivos da Cleanwatts
deactivate AlgorithmReceiver

ICCliente -> ICDecisionForwarder : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
activate ICCliente
activate ICDecisionForwarder
ICDecisionForwarder -> ICCliente : Envia Decisões
deactivate ICDecisionForwarder
deactivate ICCliente

CWDecisionForwarder -> CWCliente : Envia Decisões
activate CWDecisionForwarder
activate CWCliente
CWCliente -> CWDecisionForwarder : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
deactivate CWCliente
deactivate CWDecisionForwarder

@enduml
