@startuml LVL1
!define COLOR #5B9BD5

actor "Cleanwatts" as CWCliente COLOR
actor "i-charging" as ICCliente COLOR
participant "Translator System" as SistemaTRANS COLOR
participant "Cleanwatts" as Cleanwatts COLOR
participant "RabbitMQ (i-charging)" as RabbitIC COLOR
participant "i-charging" as ICharging COLOR
participant "Residential Decision System" as SistemaRD COLOR
participant "Training System" as SistemaTRAIN COLOR
participant "RabbitMQ (System)" as RabbitSYS COLOR

SistemaTRANS -> Cleanwatts : POST /sessions
alt Sucesso
    Cleanwatts --> SistemaTRANS : 201 Created
else Falha
    Cleanwatts --> SistemaTRANS : Erro
end
loop
    SistemaTRANS -> Cleanwatts : GET /data/lastvalue/Instant?tags=deviceID
    alt Sucesso
        Cleanwatts --> SistemaTRANS : 200 Ok
    else Falha
        Cleanwatts --> SistemaTRANS : Erro
    end
end
ICharging -> RabbitIC : Envia Dados
RabbitIC -> SistemaTRANS : Envia Dados 

SistemaTRANS -> SistemaTRANS : Processa e Agrupa Dados
SistemaTRANS -> RabbitSYS : Envia Dados Processados para Fila

RabbitSYS -> SistemaTRAIN : Envia Dados da Fila
RabbitSYS -> SistemaRD : Envia Dados da Fila

ICCliente -> SistemaRD : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
SistemaRD -> ICCliente : Envia Decisões
CWCliente -> SistemaRD : Solicita Decisões Tomadas pelo algoritmo para ajustar a carga
SistemaRD -> CWCliente : Envia Decisões

@enduml
