@startuml LV1

skinparam linetype ortho

skinparam component{
  BackgroundColor lightsteelblue
}

label "CleanWatts" as cwl
label "I-Charging" as icl

component "Decision System" <<component>>{
  port cw as " "
  port ic as " "
}


cw -up-( cwl
ic -up-( icl
@enduml