@startuml LV1

skinparam linetype ortho

skinparam component {
  BackgroundColor lightsteelblue
}

label "CleanWatts" as cwl
label "I-Charging" as icl

component "Decision System" <<component>>{
    component "Generic Residential\nDecision System" <<component>>{
        port grds as " "
    }
    component "Translator System" <<component>>{
        port ts as " "
    }
    component "Training System" <<component>>{
        port trs as " "
    }
    port cw as " "
    port ic as " "
}

[Translator System] -- ic
[Translator System] -- cw

cw -up-( cwl
ic -up-( icl


@enduml
