@startuml LV1

skinparam linetype ortho

skinparam component {
  BackgroundColor lightsteelblue
}

label "CleanWatts" as cwl
label "I-Charging" as icl
interface Home...

component "Translator System" <<component>>{
  [I-Charging Receiver]<<component>>
  [CleanWatts Receiver]<<component>>
  [I-Charging Translator]<<component>>
  [CleanWatts Translator]<<component>>
  [Accumulator]<<component>>
  port cw as " "
  port ic as " "
  port ac as " "
}

[I-Charging Receiver] -- [I-Charging Translator]
[CleanWatts Receiver] -- [CleanWatts Translator]
[I-Charging Translator] -- [Accumulator]
[CleanWatts Translator] -- [Accumulator]

[I-Charging Receiver] -- ic
[CleanWatts Receiver] -- cw
[Accumulator] -- ac

cw -up-( cwl
ic -up-( icl
ac -up- Home...


@enduml
